#include <time.h>
#include <stdlib.h>
#include <stdio.h>

int main()
{
	srand(time(NULL)); 
	int r = rand();
	printf("<html><body>This site was randomly generated by a C program\n");
	printf("<p style=\"width:100%%;margin:0 auto;\">%d</p>", r);
	printf("</body></html>");
	return 0;
}
